test = {
'home' : {
'supplies':283.840,
'money':3.600,
'crude_oil':2.200,
'metal':167.140,
'energy':669.450,
'rare_materials':43.640,
},
'technology' : {
'single_engine_aircraft_design' : 1 ,
'twin_engine_aircraft_design' : 1 ,
'basic_aeroengine' : 1 ,
'basic_small_fueltank' : 1 ,
'basic_single_engine_airframe' : 1 ,
'basic_aircraft_machinegun' : 1 ,
'basic_medium_fueltank' : 0 ,
'basic_twin_engine_airframe' : 1 ,
'basic_bomb' : 0 ,
'multi_role_fighter_development' : 0 ,
'cas_development' : 1 ,
'nav_development' : 1 ,
'basic_four_engine_airframe' : 1 ,
'basic_strategic_bomber' : 1 ,
'aeroengine' : 0 ,
'small_fueltank' : 0 ,
'single_engine_airframe' : 0 ,
'single_engine_aircraft_armament' : 0 ,
'medium_fueltank' : 0 ,
'twin_engine_airframe' : 0 ,
'air_launched_torpedo' : 0 ,
'small_bomb' : 0 ,
'twin_engine_aircraft_armament' : 0 ,
'medium_bomb' : 0 ,
'large_fueltank' : 0 ,
'four_engine_airframe' : 0 ,
'strategic_bomber_armament' : 0 ,
'cargo_hold' : 0 ,
'large_bomb' : 0 ,
'advanced_aircraft_design' : 0 ,
'small_airsearch_radar' : 0 ,
'medium_airsearch_radar' : 0 ,
'large_airsearch_radar' : 0 ,
'small_navagation_radar' : 0 ,
'medium_navagation_radar' : 0 ,
'large_navagation_radar' : 0 ,
'rocket_interceptor_tech' : 0 ,
'drop_tanks' : 0 ,
'jet_engine' : 0 ,
'fighter_pilot_training' : 2 ,
'fighter_groundcrew_training' : 2 ,
'interception_tactics' : 2 ,
'fighter_ground_control' : 0 ,
'bomber_targerting_focus' : 2 ,
'fighter_targerting_focus' : 2 ,
'cas_pilot_training' : 2 ,
'cas_groundcrew_training' : 2 ,
'ground_attack_tactics' : 2 ,
'forward_air_control' : 2 ,
'battlefield_interdiction' : 2 ,
'tac_pilot_training' : 2 ,
'tac_groundcrew_training' : 2 ,
'interdiction_tactics' : 2 ,
'logistical_strike_tactics' : 1 ,
'installation_strike_tactics' : 1 ,
'airbase_strike_tactics' : 2 ,
'tactical_air_command' : 2 ,
'nav_pilot_training' : 1 ,
'nav_groundcrew_training' : 1 ,
'portstrike_tactics' : 0 ,
'navalstrike_tactics' : 0 ,
'naval_air_targeting' : 0 ,
'naval_tactics' : 0 ,
'heavy_bomber_pilot_training' : 1 ,
'heavy_bomber_groundcrew_training' : 1 ,
'strategic_bombardment_tactics' : 1 ,
'airborne_assault_tactics' : 0 ,
'strategic_air_command' : 0 ,
'lighttank_brigade' : 1 ,
'lighttank_gun' : 1 ,
'lighttank_engine' : 1 ,
'lighttank_armour' : 1 ,
'lighttank_reliability' : 1 ,
'tank_brigade' : 0 ,
'tank_gun' : 0 ,
'tank_engine' : 0 ,
'tank_armour' : 0 ,
'tank_reliability' : 0 ,
'heavy_tank_brigade' : 0 ,
'heavy_tank_gun' : 0 ,
'heavy_tank_engine' : 0 ,
'heavy_tank_armour' : 0 ,
'heavy_tank_reliability' : 0 ,
'armored_car_armour' : 1 ,
'armored_car_gun' : 1 ,
'SP_brigade' : 0 ,
'mechanised_infantry' : 0 ,
'super_heavy_tank_brigade' : 0 ,
'super_heavy_tank_gun' : 0 ,
'super_heavy_tank_engine' : 0 ,
'super_heavy_tank_armour' : 0 ,
'super_heavy_tank_reliability' : 0 ,
'art_barrell_ammo' : 3 ,
'art_carriage_sights' : 3 ,
'at_barrell_sights' : 1 ,
'at_ammo_muzzel' : 1 ,
'aa_barrell_ammo' : 1 ,
'aa_carriage_sights' : 1 ,
'rocket_art' : 0 ,
'rocket_art_ammo' : 0 ,
'rocket_carriage_sights' : 0 ,
'mobile_warfare' : 2 ,
'elastic_defence' : 2 ,
'spearhead_doctrine' : 0 ,
'schwerpunkt' : 0 ,
'blitzkrieg' : 2 ,
'operational_level_command_structure' : 1 ,
'tactical_command_structure' : 0 ,
'delay_doctrine' : 0 ,
'integrated_support_doctrine' : 2 ,
'superior_firepower' : 0 ,
'mechanized_offensive' : 2 ,
'combined_arms_warfare' : 0 ,
'infantry_warfare' : 2 ,
'special_forces' : 1 ,
'central_planning' : 0 ,
'mass_assault' : 0 ,
'grand_battle_plan' : 0 ,
'assault_concentration' : 1 ,
'operational_level_organisation' : 1 ,
'large_front' : 0 ,
'guerilla_warfare' : 0 ,
'peoples_army' : 2 ,
'large_formations' : 0 ,
'human_wave' : 0 ,
'fleet_auxiliary_carrier_doctrine' : 0 ,
'light_cruiser_escort_role' : 0 ,
'carrier_group_doctrine' : 0 ,
'light_cruiser_crew_training' : 0 ,
'carrier_crew_training' : 0 ,
'carrier_task_force' : 0 ,
'naval_underway_repleshment' : 0 ,
'radar_training' : 0 ,
'sea_lane_defence' : 1 ,
'destroyer_escort_role' : 0 ,
'battlefleet_concentration_doctrine' : 0 ,
'destroyer_crew_training' : 0 ,
'battleship_crew_training' : 0 ,
'commerce_defence' : 0 ,
'fire_control_system_training' : 1 ,
'commander_decision_making' : 0 ,
'fleet_auxiliary_submarine_doctrine' : 1 ,
'trade_interdiction_submarine_doctrine' : 1 ,
'cruiser_warfare' : 1 ,
'submarine_crew_training' : 1 ,
'cruiser_crew_training' : 0 ,
'unrestricted_submarine_warfare_doctrine' : 0 ,
'spotting' : 0 ,
'basing' : 0 ,
'destroyer_technology' : 1 ,
'destroyer_armament' : 2 ,
'destroyer_antiaircraft' : 2 ,
'destroyer_engine' : 2 ,
'destroyer_armour' : 2 ,
'lightcruiser_technology' : 1 ,
'lightcruiser_armament' : 2 ,
'lightcruiser_antiaircraft' : 2 ,
'lightcruiser_engine' : 3 ,
'lightcruiser_armour' : 2 ,
'smallwarship_radar' : 1 ,
'smallwarship_asw' : 0 ,
'heavycruiser_technology' : 1 ,
'heavycruiser_armament' : 3 ,
'heavycruiser_antiaircraft' : 2 ,
'heavycruiser_engine' : 3 ,
'heavycruiser_armour' : 3 ,
'battlecruiser_technology' : 1 ,
'battleship_technology' : 1 ,
'capitalship_armament' : 3 ,
'battlecruiser_antiaircraft' : 2 ,
'battlecruiser_engine' : 3 ,
'battlecruiser_armour' : 3 ,
'battleship_antiaircraft' : 2 ,
'battleship_engine' : 2 ,
'battleship_armour' : 3 ,
'super_heavy_battleship_technology' : 0 ,
'cag_development' : 1 ,
'escort_carrier_technology' : 0 ,
'carrier_technology' : 0 ,
'carrier_antiaircraft' : 0 ,
'carrier_engine' : 0 ,
'carrier_armour' : 0 ,
'carrier_hanger' : 0 ,
'largewarship_radar' : 0 ,
'submarine_technology' : 1 ,
'submarine_antiaircraft' : 2 ,
'submarine_engine' : 2 ,
'submarine_hull' : 1 ,
'submarine_torpedoes' : 2 ,
'submarine_sonar' : 1 ,
'submarine_airwarningequipment' : 0 ,
'amphibious_invasion_craft' : 0 ,
'advanced_invasion_craft' : 0 ,
'amphibious_invasion_technology' : 0 ,
'amphibious_assault_units' : 0 ,
'strategic_rocket_development' : 0 ,
'flyingbomb_development' : 0 ,
'flyingrocket_development' : 0 ,
'strategicrocket_engine' : 0 ,
'strategicrocket_warhead' : 0 ,
'strategicrocket_structure' : 0 ,
'da_bomb' : 0 ,
'radar_guided_missile' : 0 ,
'radar_guided_bomb' : 0 ,
'electric_powered_torpedo' : 0 ,
'helecopters' : 0 ,
'medical_evacuation' : 0 ,
'pilot_rescue' : 0 ,
'sam' : 0 ,
'aam' : 0 ,
'naval_engineering_research' : 0 ,
'submarine_engineering_research' : 0 ,
'aeronautic_engineering_research' : 0 ,
'rocket_science_research' : 0 ,
'chemical_engineering_research' : 0 ,
'nuclear_physics_research' : 0 ,
'jetengine_research' : 0 ,
'mechanicalengineering_research' : 0 ,
'automotive_research' : 0 ,
'electornicegineering_research' : 0 ,
'artillery_research' : 0 ,
'mobile_research' : 0 ,
'militia_research' : 0 ,
'infantry_research' : 0 ,
'combat_medicine' : 1 ,
'first_aid' : 1 ,
'agriculture' : 4 ,
'industral_production' : 4 ,
'industral_efficiency' : 4 ,
'oil_to_coal_conversion' : 2 ,
'supply_production' : 4 ,
'heavy_aa_guns' : 2 ,
'electronic_mechanical_egineering' : 1 ,
'radio_technology' : 1 ,
'radio_detection_equipment' : 1 ,
'radio' : 1 ,
'radar' : 0 ,
'census_tabulation_machine' : 1 ,
'mechnical_computing_machine' : 1 ,
'electronic_computing_machine' : 0 ,
'decryption_machine' : 0 ,
'encryption_machine' : 1 ,
'construction_engineering' : 1 ,
'advanced_construction_engineering' : 1 ,
'rocket_tests' : 1 ,
'rocket_engine' : 0 ,
'theorical_jet_engine' : 0 ,
'atomic_research' : 1 ,
'nuclear_research' : 0 ,
'isotope_seperation' : 0 ,
'civil_nuclear_research' : 0 ,
'oil_refinning' : 1 ,
'steel_production' : 2 ,
'raremetal_refinning_techniques' : 2 ,
'coal_processing_technologies' : 2 ,
'education' : 1 ,
'supply_transportation' : 1 ,
'supply_organisation' : 1 ,
'civil_defence' : 1 ,
'cavalry_smallarms' : 3 ,
'cavalry_support' : 3 ,
'cavalry_guns' : 3 ,
'cavalry_at' : 3 ,
'militia_smallarms' : 1 ,
'militia_support' : 2 ,
'militia_guns' : 2 ,
'militia_at' : 2 ,
'infantry_activation' : 1 ,
'smallarms_technology' : 1 ,
'infantry_support' : 1 ,
'infantry_guns' : 1 ,
'infantry_at' : 1 ,
'mountain_infantry' : 1 ,
'marine_infantry' : 0 ,
'paratrooper_infantry' : 0 ,
'night_goggles' : 0 ,
'engineer_brigade_activation' : 1 ,
'engineer_bridging_equipment' : 0 ,
'engineer_assault_equipment' : 0 ,
'imporved_police_brigade' : 0 ,
'mortorised_infantry' : 1 ,
'desert_warfare_equipment' : 0 ,
'jungle_warfare_equipment' : 0 ,
'mountain_warfare_equipment' : 0 ,
'artic_warfare_equipment' : 0 ,
'amphibious_warfare_equipment' : 0 ,
'airborne_warfare_equipment': 0 
},
'practical' : {
'infantry_theory':10.000,
'militia_theory':2.500,
'mobile_theory':5.000,
'artillery_theory':10.000,
'rocket_science':5.000,
'submarine_engineering':10.000,
'electornicegineering_theory':5.000,
'aeronautic_engineering':10.000,
'automotive_theory':10.000,
'spearhead_theory':10.000,
'superior_firepower_theory':0.000,
'grand_battleplan_theory':0.000,
'human_wave_theory':0.000,
'base_strike_doctrine':0.000,
'fleet_in_being_doctrine':0.000,
'sealane_interdiction_doctrine':5.000,
'fighter_focus':2.500,
'cas_focus':2.500,
'tac_focus':2.500,
'nav_focus':1.000,
'strategic_air_focus':0.000,
'mechanicalengineering_theory':15.000,
'chemical_engineering':10.000,
'jetengine_theory':0.000,
'nuclear_physics':1.000,
'infantry_practical':10.000,
'militia_practical':2.500,
'mobile_practical':5.000,
'artillery_practical':10.000,
'rocket_practical':0.000,
'naval_engineering':5.000,
'destroyer_practical':5.000,
'cruiser_practical':5.000,
'capitalship_practical':2.500,
'carrier_practical':0.000,
'submarine_practical':5.000,
'electornicegineering_practical':5.000,
'armour_practical':5.000,
'single_engine_aircraft_practical':10.000,
'twin_engine_aircraft_practical':5.000,
'four_engine_aircraft_practical':2.500,
'land_doctrine_practical':1.000,
'naval_doctrine_practical':0.000,
'air_doctrine_practical':0.000,
'jetengine_practical':0.000,
'nuclear_bomb':0.000,
'transport_practical':2.500,
'construction_practical':5.000,
},
'politics' : {
'head_of_state':1,
'head_of_government':2,
'foreign_minister':3,
'armament_minister':35,
'minister_of_security':246,
'minister_of_intelligence':6,
'chief_of_staff':7,
'chief_of_army':8,
'chief_of_navy':9,
'chief_of_air':208,
'civil_law':'totalitarian_system',
'conscription_law':'two_year_draft',
'economic_law':'war_economy',
'education_investment_law':'big_education_investment',
'industrial_policy_laws':'consumer_product_orientation',
'press_laws':'propaganda_press',
'training_laws':'specialist_training',
'ideology':"national_socialist",
'manpower':882.474
},
'pool' :
{
'supplies' : 8410.780,
'money' : 40.050,
'crude_oil' : 13234.496,
'fuel':5833.290,
'metal':13500.792,
'energy':27604.932,
'rare_materials':46670.542
}
}
